volumes:
  shared_data:

services:
  activation:
    image: ${DOCKER_NAMESPACE}/activationbase_pradar
    volumes:
      - shared_data:/tmp

  knowledge:
    image: ${DOCKER_NAMESPACE}/knowledgebase_pradar
    volumes:
      - shared_data:/tmp

  code:
    image: ${DOCKER_NAMESPACE}/codebase_pradar
    volumes:
      - shared_data:/tmp
    depends_on:
      - activation
      - knowledge